package migrations

import (
	"github.com/udovin/solve/internal/db"
	"github.com/udovin/solve/internal/db/schema"
)

func init() {
	Schema.AddMigration("001_initial", db.NewMigration(s001))
}

var s001 = []schema.Operation{
	schema.CreateTable{
		Name: "solve_setting",
		Columns: []schema.Column{
			{Name: "id", Type: schema.Int64, PrimaryKey: true, AutoIncrement: true},
			{Name: "key", Type: schema.String},
			{Name: "value", Type: schema.String},
		},
	},
	schema.CreateIndex{
		Table:   "solve_setting",
		Columns: []string{"key"},
		Unique:  true,
	},
	schema.CreateTable{
		Name: "solve_setting_event",
		Columns: []schema.Column{
			{Name: "event_id", Type: schema.Int64, PrimaryKey: true, AutoIncrement: true},
			{Name: "event_kind", Type: schema.Int64},
			{Name: "event_time", Type: schema.Int64},
			{Name: "event_account_id", Type: schema.Int64, Nullable: true},
			{Name: "id", Type: schema.Int64},
			{Name: "key", Type: schema.String},
			{Name: "value", Type: schema.String},
		},
	},
	schema.CreateIndex{
		Table:   "solve_setting_event",
		Columns: []string{"id", "event_id"},
	},
	schema.CreateTable{
		Name: "solve_task",
		Columns: []schema.Column{
			{Name: "id", Type: schema.Int64, PrimaryKey: true, AutoIncrement: true},
			{Name: "status", Type: schema.Int64},
			{Name: "kind", Type: schema.Int64},
			{Name: "config", Type: schema.JSON},
			{Name: "state", Type: schema.JSON},
			{Name: "expire_time", Type: schema.Int64, Nullable: true},
		},
	},
	schema.CreateIndex{
		Table:   "solve_task",
		Columns: []string{"status"},
	},
	schema.CreateTable{
		Name: "solve_task_event",
		Columns: []schema.Column{
			{Name: "event_id", Type: schema.Int64, PrimaryKey: true, AutoIncrement: true},
			{Name: "event_kind", Type: schema.Int64},
			{Name: "event_time", Type: schema.Int64},
			{Name: "event_account_id", Type: schema.Int64, Nullable: true},
			{Name: "id", Type: schema.Int64},
			{Name: "status", Type: schema.Int64},
			{Name: "kind", Type: schema.Int64},
			{Name: "config", Type: schema.JSON},
			{Name: "state", Type: schema.JSON},
			{Name: "expire_time", Type: schema.Int64, Nullable: true},
		},
	},
	schema.CreateIndex{
		Table:   "solve_task_event",
		Columns: []string{"id", "event_id"},
	},
	schema.CreateTable{
		Name: "solve_lock",
		Columns: []schema.Column{
			{Name: "id", Type: schema.Int64, PrimaryKey: true, AutoIncrement: true},
			{Name: "name", Type: schema.String},
			{Name: "token", Type: schema.Int64},
			{Name: "expire_time", Type: schema.Int64},
		},
	},
	schema.CreateIndex{
		Table:   "solve_lock",
		Columns: []string{"name"},
		Unique:  true,
	},
	schema.CreateTable{
		Name: "solve_file",
		Columns: []schema.Column{
			{Name: "id", Type: schema.Int64, PrimaryKey: true, AutoIncrement: true},
			{Name: "status", Type: schema.Int64},
			{Name: "expire_time", Type: schema.Int64, Nullable: true},
			{Name: "path", Type: schema.String},
			{Name: "meta", Type: schema.JSON},
		},
	},
	schema.CreateIndex{
		Table:   "solve_file",
		Columns: []string{"path"},
		Unique:  true,
	},
	schema.CreateTable{
		Name: "solve_file_event",
		Columns: []schema.Column{
			{Name: "event_id", Type: schema.Int64, PrimaryKey: true, AutoIncrement: true},
			{Name: "event_kind", Type: schema.Int64},
			{Name: "event_time", Type: schema.Int64},
			{Name: "event_account_id", Type: schema.Int64, Nullable: true},
			{Name: "id", Type: schema.Int64},
			{Name: "status", Type: schema.Int64},
			{Name: "expire_time", Type: schema.Int64, Nullable: true},
			{Name: "path", Type: schema.String},
			{Name: "meta", Type: schema.JSON},
		},
	},
	schema.CreateIndex{
		Table:   "solve_file_event",
		Columns: []string{"id", "event_id"},
	},
	schema.CreateTable{
		Name: "solve_role",
		Columns: []schema.Column{
			{Name: "id", Type: schema.Int64, PrimaryKey: true, AutoIncrement: true},
			{Name: "name", Type: schema.String},
		},
	},
	schema.CreateIndex{
		Table:   "solve_role",
		Columns: []string{"name"},
		Unique:  true,
	},
	schema.CreateTable{
		Name: "solve_role_event",
		Columns: []schema.Column{
			{Name: "event_id", Type: schema.Int64, PrimaryKey: true, AutoIncrement: true},
			{Name: "event_kind", Type: schema.Int64},
			{Name: "event_time", Type: schema.Int64},
			{Name: "event_account_id", Type: schema.Int64, Nullable: true},
			{Name: "id", Type: schema.Int64},
			{Name: "name", Type: schema.String},
		},
	},
	schema.CreateIndex{
		Table:   "solve_role_event",
		Columns: []string{"id", "event_id"},
	},
	schema.CreateTable{
		Name: "solve_role_edge",
		Columns: []schema.Column{
			{Name: "id", Type: schema.Int64, PrimaryKey: true, AutoIncrement: true},
			{Name: "role_id", Type: schema.Int64},
			{Name: "child_id", Type: schema.Int64},
		},
		ForeignKeys: []schema.ForeignKey{
			{Column: "role_id", ParentTable: "solve_role", ParentColumn: "id"},
			{Column: "child_id", ParentTable: "solve_role", ParentColumn: "id"},
		},
	},
	schema.CreateIndex{
		Table:   "solve_role_edge",
		Columns: []string{"role_id", "child_id"},
		Unique:  true,
	},
	schema.CreateTable{
		Name: "solve_role_edge_event",
		Columns: []schema.Column{
			{Name: "event_id", Type: schema.Int64, PrimaryKey: true, AutoIncrement: true},
			{Name: "event_kind", Type: schema.Int64},
			{Name: "event_time", Type: schema.Int64},
			{Name: "event_account_id", Type: schema.Int64, Nullable: true},
			{Name: "id", Type: schema.Int64},
			{Name: "role_id", Type: schema.Int64},
			{Name: "child_id", Type: schema.Int64},
		},
	},
	schema.CreateIndex{
		Table:   "solve_role_edge_event",
		Columns: []string{"id", "event_id"},
	},
	schema.CreateTable{
		Name: "solve_account",
		Columns: []schema.Column{
			{Name: "id", Type: schema.Int64, PrimaryKey: true, AutoIncrement: true},
			{Name: "kind", Type: schema.Int64},
		},
	},
	schema.CreateTable{
		Name: "solve_account_event",
		Columns: []schema.Column{
			{Name: "event_id", Type: schema.Int64, PrimaryKey: true, AutoIncrement: true},
			{Name: "event_kind", Type: schema.Int64},
			{Name: "event_time", Type: schema.Int64},
			{Name: "event_account_id", Type: schema.Int64, Nullable: true},
			{Name: "id", Type: schema.Int64},
			{Name: "kind", Type: schema.Int64},
		},
	},
	schema.CreateIndex{
		Table:   "solve_account_event",
		Columns: []string{"id", "event_id"},
	},
	schema.CreateTable{
		Name: "solve_account_role",
		Columns: []schema.Column{
			{Name: "id", Type: schema.Int64, PrimaryKey: true, AutoIncrement: true},
			{Name: "account_id", Type: schema.Int64},
			{Name: "role_id", Type: schema.Int64},
		},
		ForeignKeys: []schema.ForeignKey{
			{Column: "account_id", ParentTable: "solve_account", ParentColumn: "id"},
			{Column: "role_id", ParentTable: "solve_role", ParentColumn: "id"},
		},
	},
	schema.CreateIndex{
		Table:   "solve_account_role",
		Columns: []string{"account_id", "role_id"},
		Unique:  true,
	},
	schema.CreateTable{
		Name: "solve_account_role_event",
		Columns: []schema.Column{
			{Name: "event_id", Type: schema.Int64, PrimaryKey: true, AutoIncrement: true},
			{Name: "event_kind", Type: schema.Int64},
			{Name: "event_time", Type: schema.Int64},
			{Name: "event_account_id", Type: schema.Int64, Nullable: true},
			{Name: "id", Type: schema.Int64},
			{Name: "account_id", Type: schema.Int64},
			{Name: "role_id", Type: schema.Int64},
		},
	},
	schema.CreateIndex{
		Table:   "solve_account_role_event",
		Columns: []string{"id", "event_id"},
	},
	schema.CreateTable{
		Name: "solve_session",
		Columns: []schema.Column{
			{Name: "id", Type: schema.Int64, PrimaryKey: true, AutoIncrement: true},
			{Name: "account_id", Type: schema.Int64},
			{Name: "secret", Type: schema.String},
			{Name: "create_time", Type: schema.Int64},
			{Name: "expire_time", Type: schema.Int64},
			{Name: "real_ip", Type: schema.String},
			{Name: "user_agent", Type: schema.String},
		},
		ForeignKeys: []schema.ForeignKey{
			{Column: "account_id", ParentTable: "solve_account", ParentColumn: "id"},
		},
	},
	schema.CreateIndex{
		Table:   "solve_session",
		Columns: []string{"expire_time"},
	},
	schema.CreateTable{
		Name: "solve_session_event",
		Columns: []schema.Column{
			{Name: "event_id", Type: schema.Int64, PrimaryKey: true, AutoIncrement: true},
			{Name: "event_kind", Type: schema.Int64},
			{Name: "event_time", Type: schema.Int64},
			{Name: "event_account_id", Type: schema.Int64, Nullable: true},
			{Name: "id", Type: schema.Int64},
			{Name: "account_id", Type: schema.Int64},
			{Name: "secret", Type: schema.String},
			{Name: "create_time", Type: schema.Int64},
			{Name: "expire_time", Type: schema.Int64},
			{Name: "real_ip", Type: schema.String},
			{Name: "user_agent", Type: schema.String},
		},
	},
	schema.CreateIndex{
		Table:   "solve_session_event",
		Columns: []string{"id", "event_id"},
	},
	schema.CreateTable{
		Name: "solve_token",
		Columns: []schema.Column{
			{Name: "id", Type: schema.Int64, PrimaryKey: true, AutoIncrement: true},
			{Name: "account_id", Type: schema.Int64},
			{Name: "secret", Type: schema.String},
			{Name: "kind", Type: schema.Int64},
			{Name: "config", Type: schema.JSON},
			{Name: "create_time", Type: schema.Int64},
			{Name: "expire_time", Type: schema.Int64},
		},
		ForeignKeys: []schema.ForeignKey{
			{Column: "account_id", ParentTable: "solve_account", ParentColumn: "id"},
		},
	},
	schema.CreateTable{
		Name: "solve_token_event",
		Columns: []schema.Column{
			{Name: "event_id", Type: schema.Int64, PrimaryKey: true, AutoIncrement: true},
			{Name: "event_kind", Type: schema.Int64},
			{Name: "event_time", Type: schema.Int64},
			{Name: "event_account_id", Type: schema.Int64, Nullable: true},
			{Name: "id", Type: schema.Int64},
			{Name: "account_id", Type: schema.Int64},
			{Name: "secret", Type: schema.String},
			{Name: "kind", Type: schema.Int64},
			{Name: "config", Type: schema.JSON},
			{Name: "create_time", Type: schema.Int64},
			{Name: "expire_time", Type: schema.Int64},
		},
	},
	schema.CreateIndex{
		Table:   "solve_token_event",
		Columns: []string{"id", "event_id"},
	},
	schema.CreateTable{
		Name: "solve_user",
		Columns: []schema.Column{
			{Name: "id", Type: schema.Int64, PrimaryKey: true},
			{Name: "login", Type: schema.String},
			{Name: "status", Type: schema.Int64},
			{Name: "password_hash", Type: schema.String},
			{Name: "password_salt", Type: schema.String},
			{Name: "email", Type: schema.String, Nullable: true},
			{Name: "first_name", Type: schema.String, Nullable: true},
			{Name: "last_name", Type: schema.String, Nullable: true},
			{Name: "middle_name", Type: schema.String, Nullable: true},
		},
		ForeignKeys: []schema.ForeignKey{
			{Column: "id", ParentTable: "solve_account", ParentColumn: "id"},
		},
	},
	schema.CreateIndex{
		Table:      "solve_user",
		Expression: "LOWER(\"login\")",
		Unique:     true,
	},
	schema.CreateIndex{
		Table:      "solve_user",
		Expression: "LOWER(\"email\")",
		Unique:     true,
	},
	schema.CreateTable{
		Name: "solve_user_event",
		Columns: []schema.Column{
			{Name: "event_id", Type: schema.Int64, PrimaryKey: true, AutoIncrement: true},
			{Name: "event_kind", Type: schema.Int64},
			{Name: "event_time", Type: schema.Int64},
			{Name: "event_account_id", Type: schema.Int64, Nullable: true},
			{Name: "id", Type: schema.Int64},
			{Name: "login", Type: schema.String},
			{Name: "status", Type: schema.Int64},
			{Name: "password_hash", Type: schema.String},
			{Name: "password_salt", Type: schema.String},
			{Name: "email", Type: schema.String, Nullable: true},
			{Name: "first_name", Type: schema.String, Nullable: true},
			{Name: "last_name", Type: schema.String, Nullable: true},
			{Name: "middle_name", Type: schema.String, Nullable: true},
		},
	},
	schema.CreateIndex{
		Table:   "solve_user_event",
		Columns: []string{"id", "event_id"},
	},
	schema.CreateTable{
		Name: "solve_scope",
		Columns: []schema.Column{
			{Name: "id", Type: schema.Int64, PrimaryKey: true},
			{Name: "owner_id", Type: schema.Int64, Nullable: true},
			{Name: "title", Type: schema.String},
		},
		ForeignKeys: []schema.ForeignKey{
			{Column: "id", ParentTable: "solve_account", ParentColumn: "id"},
			{Column: "owner_id", ParentTable: "solve_account", ParentColumn: "id"},
		},
	},
	schema.CreateTable{
		Name: "solve_scope_event",
		Columns: []schema.Column{
			{Name: "event_id", Type: schema.Int64, PrimaryKey: true, AutoIncrement: true},
			{Name: "event_kind", Type: schema.Int64},
			{Name: "event_time", Type: schema.Int64},
			{Name: "event_account_id", Type: schema.Int64, Nullable: true},
			{Name: "id", Type: schema.Int64},
			{Name: "owner_id", Type: schema.Int64, Nullable: true},
			{Name: "title", Type: schema.String},
		},
	},
	schema.CreateIndex{
		Table:   "solve_scope_event",
		Columns: []string{"id", "event_id"},
	},
	schema.CreateTable{
		Name: "solve_scope_user",
		Columns: []schema.Column{
			{Name: "id", Type: schema.Int64, PrimaryKey: true},
			{Name: "scope_id", Type: schema.Int64},
			{Name: "login", Type: schema.String},
			{Name: "password_hash", Type: schema.String},
			{Name: "password_salt", Type: schema.String},
			{Name: "title", Type: schema.String, Nullable: true},
		},
		ForeignKeys: []schema.ForeignKey{
			{Column: "id", ParentTable: "solve_account", ParentColumn: "id"},
			{Column: "scope_id", ParentTable: "solve_scope", ParentColumn: "id"},
		},
	},
	schema.CreateIndex{
		Table:      "solve_scope_user",
		Expression: "\"scope_id\", LOWER(\"login\")",
		Unique:     true,
	},
	schema.CreateTable{
		Name: "solve_scope_user_event",
		Columns: []schema.Column{
			{Name: "event_id", Type: schema.Int64, PrimaryKey: true, AutoIncrement: true},
			{Name: "event_kind", Type: schema.Int64},
			{Name: "event_time", Type: schema.Int64},
			{Name: "event_account_id", Type: schema.Int64, Nullable: true},
			{Name: "id", Type: schema.Int64},
			{Name: "scope_id", Type: schema.Int64},
			{Name: "login", Type: schema.String},
			{Name: "password_hash", Type: schema.String},
			{Name: "password_salt", Type: schema.String},
			{Name: "title", Type: schema.String, Nullable: true},
		},
	},
	schema.CreateIndex{
		Table:   "solve_scope_user_event",
		Columns: []string{"id", "event_id"},
	},
	schema.CreateTable{
		Name: "solve_group",
		Columns: []schema.Column{
			{Name: "id", Type: schema.Int64, PrimaryKey: true},
			{Name: "owner_id", Type: schema.Int64, Nullable: true},
			{Name: "title", Type: schema.String},
		},
		ForeignKeys: []schema.ForeignKey{
			{Column: "id", ParentTable: "solve_account", ParentColumn: "id"},
			{Column: "owner_id", ParentTable: "solve_account", ParentColumn: "id"},
		},
	},
	schema.CreateTable{
		Name: "solve_group_event",
		Columns: []schema.Column{
			{Name: "event_id", Type: schema.Int64, PrimaryKey: true, AutoIncrement: true},
			{Name: "event_kind", Type: schema.Int64},
			{Name: "event_time", Type: schema.Int64},
			{Name: "event_account_id", Type: schema.Int64, Nullable: true},
			{Name: "id", Type: schema.Int64},
			{Name: "owner_id", Type: schema.Int64, Nullable: true},
			{Name: "title", Type: schema.String},
		},
	},
	schema.CreateIndex{
		Table:   "solve_group_event",
		Columns: []string{"id", "event_id"},
	},
	schema.CreateTable{
		Name: "solve_group_member",
		Columns: []schema.Column{
			{Name: "id", Type: schema.Int64, PrimaryKey: true, AutoIncrement: true},
			{Name: "group_id", Type: schema.Int64},
			{Name: "account_id", Type: schema.Int64},
			{Name: "kind", Type: schema.Int64},
		},
		ForeignKeys: []schema.ForeignKey{
			{Column: "group_id", ParentTable: "solve_group", ParentColumn: "id"},
			{Column: "account_id", ParentTable: "solve_account", ParentColumn: "id"},
		},
	},
	schema.CreateIndex{
		Table:   "solve_group_member",
		Columns: []string{"group_id", "account_id"},
		Unique:  true,
	},
	schema.CreateIndex{
		Table:   "solve_group_member",
		Columns: []string{"account_id"},
	},
	schema.CreateTable{
		Name: "solve_group_member_event",
		Columns: []schema.Column{
			{Name: "event_id", Type: schema.Int64, PrimaryKey: true, AutoIncrement: true},
			{Name: "event_kind", Type: schema.Int64},
			{Name: "event_time", Type: schema.Int64},
			{Name: "event_account_id", Type: schema.Int64, Nullable: true},
			{Name: "id", Type: schema.Int64},
			{Name: "group_id", Type: schema.Int64},
			{Name: "account_id", Type: schema.Int64},
			{Name: "kind", Type: schema.Int64},
		},
	},
	schema.CreateIndex{
		Table:   "solve_group_member_event",
		Columns: []string{"id", "event_id"},
	},
	schema.CreateTable{
		Name: "solve_contest",
		Columns: []schema.Column{
			{Name: "id", Type: schema.Int64, PrimaryKey: true, AutoIncrement: true},
			{Name: "owner_id", Type: schema.Int64, Nullable: true},
			{Name: "config", Type: schema.JSON},
			{Name: "title", Type: schema.String},
		},
		ForeignKeys: []schema.ForeignKey{
			{Column: "owner_id", ParentTable: "solve_account", ParentColumn: "id"},
		},
	},
	schema.CreateTable{
		Name: "solve_contest_event",
		Columns: []schema.Column{
			{Name: "event_id", Type: schema.Int64, PrimaryKey: true, AutoIncrement: true},
			{Name: "event_kind", Type: schema.Int64},
			{Name: "event_time", Type: schema.Int64},
			{Name: "event_account_id", Type: schema.Int64, Nullable: true},
			{Name: "id", Type: schema.Int64},
			{Name: "owner_id", Type: schema.Int64, Nullable: true},
			{Name: "config", Type: schema.JSON},
			{Name: "title", Type: schema.String},
		},
	},
	schema.CreateIndex{
		Table:   "solve_contest_event",
		Columns: []string{"id", "event_id"},
	},
	schema.CreateTable{
		Name: "solve_compiler",
		Columns: []schema.Column{
			{Name: "id", Type: schema.Int64, PrimaryKey: true, AutoIncrement: true},
			{Name: "owner_id", Type: schema.Int64, Nullable: true},
			{Name: "name", Type: schema.String},
			{Name: "config", Type: schema.JSON},
			{Name: "image_id", Type: schema.Int64},
		},
		ForeignKeys: []schema.ForeignKey{
			{Column: "owner_id", ParentTable: "solve_account", ParentColumn: "id"},
			{Column: "image_id", ParentTable: "solve_file", ParentColumn: "id"},
		},
	},
	schema.CreateIndex{
		Table:   "solve_compiler",
		Columns: []string{"name"},
		Unique:  true,
	},
	schema.CreateTable{
		Name: "solve_compiler_event",
		Columns: []schema.Column{
			{Name: "event_id", Type: schema.Int64, PrimaryKey: true, AutoIncrement: true},
			{Name: "event_kind", Type: schema.Int64},
			{Name: "event_time", Type: schema.Int64},
			{Name: "event_account_id", Type: schema.Int64, Nullable: true},
			{Name: "id", Type: schema.Int64},
			{Name: "owner_id", Type: schema.Int64, Nullable: true},
			{Name: "name", Type: schema.String},
			{Name: "config", Type: schema.JSON},
			{Name: "image_id", Type: schema.Int64},
		},
	},
	schema.CreateIndex{
		Table:   "solve_compiler_event",
		Columns: []string{"id", "event_id"},
	},
	schema.CreateTable{
		Name: "solve_problem",
		Columns: []schema.Column{
			{Name: "id", Type: schema.Int64, PrimaryKey: true, AutoIncrement: true},
			{Name: "owner_id", Type: schema.Int64, Nullable: true},
			{Name: "config", Type: schema.JSON},
			{Name: "title", Type: schema.String},
			{Name: "package_id", Type: schema.Int64, Nullable: true},
			{Name: "compiled_id", Type: schema.Int64, Nullable: true},
		},
		ForeignKeys: []schema.ForeignKey{
			{Column: "owner_id", ParentTable: "solve_account", ParentColumn: "id"},
			{Column: "package_id", ParentTable: "solve_file", ParentColumn: "id"},
			{Column: "compiled_id", ParentTable: "solve_file", ParentColumn: "id"},
		},
	},
	schema.CreateTable{
		Name: "solve_problem_event",
		Columns: []schema.Column{
			{Name: "event_id", Type: schema.Int64, PrimaryKey: true, AutoIncrement: true},
			{Name: "event_kind", Type: schema.Int64},
			{Name: "event_time", Type: schema.Int64},
			{Name: "event_account_id", Type: schema.Int64, Nullable: true},
			{Name: "id", Type: schema.Int64},
			{Name: "owner_id", Type: schema.Int64, Nullable: true},
			{Name: "config", Type: schema.JSON},
			{Name: "title", Type: schema.String},
			{Name: "package_id", Type: schema.Int64, Nullable: true},
			{Name: "compiled_id", Type: schema.Int64, Nullable: true},
		},
	},
	schema.CreateIndex{
		Table:   "solve_problem_event",
		Columns: []string{"id", "event_id"},
	},
	schema.CreateTable{
		Name: "solve_problem_resource",
		Columns: []schema.Column{
			{Name: "id", Type: schema.Int64, PrimaryKey: true, AutoIncrement: true},
			{Name: "problem_id", Type: schema.Int64},
			{Name: "kind", Type: schema.Int64},
			{Name: "config", Type: schema.JSON},
			{Name: "file_id", Type: schema.Int64, Nullable: true},
		},
		ForeignKeys: []schema.ForeignKey{
			{Column: "problem_id", ParentTable: "solve_problem", ParentColumn: "id"},
			{Column: "file_id", ParentTable: "solve_file", ParentColumn: "id"},
		},
	},
	schema.CreateTable{
		Name: "solve_problem_resource_event",
		Columns: []schema.Column{
			{Name: "event_id", Type: schema.Int64, PrimaryKey: true, AutoIncrement: true},
			{Name: "event_kind", Type: schema.Int64},
			{Name: "event_time", Type: schema.Int64},
			{Name: "event_account_id", Type: schema.Int64, Nullable: true},
			{Name: "id", Type: schema.Int64},
			{Name: "problem_id", Type: schema.Int64},
			{Name: "kind", Type: schema.Int64},
			{Name: "config", Type: schema.JSON},
			{Name: "file_id", Type: schema.Int64, Nullable: true},
		},
	},
	schema.CreateIndex{
		Table:   "solve_problem_resource_event",
		Columns: []string{"id", "event_id"},
	},
	schema.CreateTable{
		Name: "solve_solution",
		Columns: []schema.Column{
			{Name: "id", Type: schema.Int64, PrimaryKey: true, AutoIncrement: true},
			{Name: "kind", Type: schema.Int64},
			{Name: "problem_id", Type: schema.Int64},
			{Name: "compiler_id", Type: schema.Int64},
			{Name: "author_id", Type: schema.Int64},
			{Name: "report", Type: schema.JSON},
			{Name: "create_time", Type: schema.Int64},
			{Name: "content", Type: schema.String, Nullable: true},
			{Name: "content_id", Type: schema.Int64, Nullable: true},
		},
		ForeignKeys: []schema.ForeignKey{
			{Column: "problem_id", ParentTable: "solve_problem", ParentColumn: "id"},
			{Column: "compiler_id", ParentTable: "solve_compiler", ParentColumn: "id"},
			{Column: "author_id", ParentTable: "solve_account", ParentColumn: "id"},
			{Column: "content_id", ParentTable: "solve_file", ParentColumn: "id"},
		},
	},
	schema.CreateTable{
		Name: "solve_solution_event",
		Columns: []schema.Column{
			{Name: "event_id", Type: schema.Int64, PrimaryKey: true, AutoIncrement: true},
			{Name: "event_kind", Type: schema.Int64},
			{Name: "event_time", Type: schema.Int64},
			{Name: "event_account_id", Type: schema.Int64, Nullable: true},
			{Name: "id", Type: schema.Int64},
			{Name: "kind", Type: schema.Int64},
			{Name: "problem_id", Type: schema.Int64},
			{Name: "compiler_id", Type: schema.Int64},
			{Name: "author_id", Type: schema.Int64},
			{Name: "report", Type: schema.JSON},
			{Name: "create_time", Type: schema.Int64},
			{Name: "content", Type: schema.String, Nullable: true},
			{Name: "content_id", Type: schema.Int64, Nullable: true},
		},
	},
	schema.CreateIndex{
		Table:   "solve_solution_event",
		Columns: []string{"id", "event_id"},
	},
	schema.CreateTable{
		Name: "solve_contest_problem",
		Columns: []schema.Column{
			{Name: "id", Type: schema.Int64, PrimaryKey: true, AutoIncrement: true},
			{Name: "contest_id", Type: schema.Int64},
			{Name: "problem_id", Type: schema.Int64},
			{Name: "code", Type: schema.String},
			{Name: "config", Type: schema.JSON},
		},
		ForeignKeys: []schema.ForeignKey{
			{Column: "contest_id", ParentTable: "solve_contest", ParentColumn: "id"},
			{Column: "problem_id", ParentTable: "solve_problem", ParentColumn: "id"},
		},
	},
	schema.CreateIndex{
		Table:   "solve_contest_problem",
		Columns: []string{"contest_id", "problem_id"},
		Unique:  true,
	},
	schema.CreateIndex{
		Table:   "solve_contest_problem",
		Columns: []string{"contest_id", "code"},
		Unique:  true,
	},
	schema.CreateTable{
		Name: "solve_contest_problem_event",
		Columns: []schema.Column{
			{Name: "event_id", Type: schema.Int64, PrimaryKey: true, AutoIncrement: true},
			{Name: "event_kind", Type: schema.Int64},
			{Name: "event_time", Type: schema.Int64},
			{Name: "event_account_id", Type: schema.Int64, Nullable: true},
			{Name: "id", Type: schema.Int64},
			{Name: "contest_id", Type: schema.Int64},
			{Name: "problem_id", Type: schema.Int64},
			{Name: "code", Type: schema.String},
			{Name: "config", Type: schema.JSON},
		},
	},
	schema.CreateIndex{
		Table:   "solve_contest_problem_event",
		Columns: []string{"id", "event_id"},
	},
	schema.CreateTable{
		Name: "solve_contest_participant",
		Columns: []schema.Column{
			{Name: "id", Type: schema.Int64, PrimaryKey: true, AutoIncrement: true},
			{Name: "contest_id", Type: schema.Int64},
			{Name: "account_id", Type: schema.Int64},
			{Name: "kind", Type: schema.Int64},
			{Name: "config", Type: schema.JSON},
		},
		ForeignKeys: []schema.ForeignKey{
			{Column: "contest_id", ParentTable: "solve_contest", ParentColumn: "id"},
			{Column: "account_id", ParentTable: "solve_account", ParentColumn: "id"},
		},
	},
	schema.CreateIndex{
		Table:   "solve_contest_participant",
		Columns: []string{"contest_id", "account_id", "kind"},
		Unique:  true,
	},
	schema.CreateTable{
		Name: "solve_contest_participant_event",
		Columns: []schema.Column{
			{Name: "event_id", Type: schema.Int64, PrimaryKey: true, AutoIncrement: true},
			{Name: "event_kind", Type: schema.Int64},
			{Name: "event_time", Type: schema.Int64},
			{Name: "event_account_id", Type: schema.Int64, Nullable: true},
			{Name: "id", Type: schema.Int64},
			{Name: "contest_id", Type: schema.Int64},
			{Name: "account_id", Type: schema.Int64},
			{Name: "kind", Type: schema.Int64},
			{Name: "config", Type: schema.JSON},
		},
	},
	schema.CreateIndex{
		Table:   "solve_contest_participant_event",
		Columns: []string{"id", "event_id"},
	},
	schema.CreateTable{
		Name: "solve_contest_solution",
		Columns: []schema.Column{
			{Name: "id", Type: schema.Int64, PrimaryKey: true},
			{Name: "contest_id", Type: schema.Int64},
			{Name: "participant_id", Type: schema.Int64},
			{Name: "problem_id", Type: schema.Int64},
		},
		ForeignKeys: []schema.ForeignKey{
			{Column: "id", ParentTable: "solve_solution", ParentColumn: "id"},
			{Column: "contest_id", ParentTable: "solve_contest", ParentColumn: "id"},
			{Column: "participant_id", ParentTable: "solve_contest_participant", ParentColumn: "id"},
			{Column: "problem_id", ParentTable: "solve_contest_problem", ParentColumn: "id"},
		},
	},
	schema.CreateTable{
		Name: "solve_contest_solution_event",
		Columns: []schema.Column{
			{Name: "event_id", Type: schema.Int64, PrimaryKey: true, AutoIncrement: true},
			{Name: "event_kind", Type: schema.Int64},
			{Name: "event_time", Type: schema.Int64},
			{Name: "event_account_id", Type: schema.Int64, Nullable: true},
			{Name: "id", Type: schema.Int64},
			{Name: "contest_id", Type: schema.Int64},
			{Name: "participant_id", Type: schema.Int64},
			{Name: "problem_id", Type: schema.Int64},
		},
	},
	schema.CreateIndex{
		Table:   "solve_contest_solution_event",
		Columns: []string{"id", "event_id"},
	},
	schema.CreateTable{
		Name: "solve_contest_message",
		Columns: []schema.Column{
			{Name: "id", Type: schema.Int64, PrimaryKey: true, AutoIncrement: true},
			{Name: "contest_id", Type: schema.Int64},
			{Name: "participant_id", Type: schema.Int64, Nullable: true},
			{Name: "author_id", Type: schema.Int64},
			{Name: "kind", Type: schema.Int64},
			{Name: "parent_id", Type: schema.Int64, Nullable: true},
			{Name: "title", Type: schema.String},
			{Name: "description", Type: schema.String},
			{Name: "create_time", Type: schema.Int64},
			{Name: "problem_id", Type: schema.Int64, Nullable: true},
		},
		ForeignKeys: []schema.ForeignKey{
			{Column: "contest_id", ParentTable: "solve_contest", ParentColumn: "id"},
			{Column: "participant_id", ParentTable: "solve_contest_participant", ParentColumn: "id"},
			{Column: "author_id", ParentTable: "solve_account", ParentColumn: "id"},
			{Column: "parent_id", ParentTable: "solve_contest_message", ParentColumn: "id"},
			{Column: "problem_id", ParentTable: "solve_contest_problem", ParentColumn: "id"},
		},
	},
	schema.CreateTable{
		Name: "solve_contest_message_event",
		Columns: []schema.Column{
			{Name: "event_id", Type: schema.Int64, PrimaryKey: true, AutoIncrement: true},
			{Name: "event_kind", Type: schema.Int64},
			{Name: "event_time", Type: schema.Int64},
			{Name: "event_account_id", Type: schema.Int64, Nullable: true},
			{Name: "id", Type: schema.Int64},
			{Name: "contest_id", Type: schema.Int64},
			{Name: "participant_id", Type: schema.Int64, Nullable: true},
			{Name: "author_id", Type: schema.Int64},
			{Name: "kind", Type: schema.Int64},
			{Name: "parent_id", Type: schema.Int64, Nullable: true},
			{Name: "title", Type: schema.String},
			{Name: "description", Type: schema.String},
			{Name: "create_time", Type: schema.Int64},
			{Name: "problem_id", Type: schema.Int64, Nullable: true},
		},
	},
	schema.CreateIndex{
		Table:   "solve_contest_message_event",
		Columns: []string{"id", "event_id"},
	},
	schema.CreateTable{
		Name: "solve_post",
		Columns: []schema.Column{
			{Name: "id", Type: schema.Int64, PrimaryKey: true, AutoIncrement: true},
			{Name: "owner_id", Type: schema.Int64, Nullable: true},
			{Name: "title", Type: schema.String},
			{Name: "description", Type: schema.String},
			{Name: "create_time", Type: schema.Int64},
			{Name: "publish_time", Type: schema.Int64, Nullable: true},
		},
		ForeignKeys: []schema.ForeignKey{
			{Column: "owner_id", ParentTable: "solve_account", ParentColumn: "id"},
		},
	},
	schema.CreateIndex{
		Table:   "solve_post",
		Columns: []string{"owner_id", "id"},
	},
	schema.CreateTable{
		Name: "solve_post_event",
		Columns: []schema.Column{
			{Name: "event_id", Type: schema.Int64, PrimaryKey: true, AutoIncrement: true},
			{Name: "event_kind", Type: schema.Int64},
			{Name: "event_time", Type: schema.Int64},
			{Name: "event_account_id", Type: schema.Int64, Nullable: true},
			{Name: "id", Type: schema.Int64},
			{Name: "owner_id", Type: schema.Int64, Nullable: true},
			{Name: "title", Type: schema.String},
			{Name: "description", Type: schema.String},
			{Name: "create_time", Type: schema.Int64},
			{Name: "publish_time", Type: schema.Int64, Nullable: true},
		},
	},
	schema.CreateIndex{
		Table:   "solve_post_event",
		Columns: []string{"id", "event_id"},
	},
	schema.CreateTable{
		Name: "solve_post_file",
		Columns: []schema.Column{
			{Name: "id", Type: schema.Int64, PrimaryKey: true, AutoIncrement: true},
			{Name: "post_id", Type: schema.Int64},
			{Name: "file_id", Type: schema.Int64},
			{Name: "name", Type: schema.String},
		},
		ForeignKeys: []schema.ForeignKey{
			{Column: "post_id", ParentTable: "solve_post", ParentColumn: "id"},
			{Column: "file_id", ParentTable: "solve_file", ParentColumn: "id"},
		},
	},
	schema.CreateIndex{
		Table:   "solve_post_file",
		Columns: []string{"post_id", "name"},
		Unique:  true,
	},
	schema.CreateTable{
		Name: "solve_post_file_event",
		Columns: []schema.Column{
			{Name: "event_id", Type: schema.Int64, PrimaryKey: true, AutoIncrement: true},
			{Name: "event_kind", Type: schema.Int64},
			{Name: "event_time", Type: schema.Int64},
			{Name: "event_account_id", Type: schema.Int64, Nullable: true},
			{Name: "id", Type: schema.Int64},
			{Name: "post_id", Type: schema.Int64},
			{Name: "file_id", Type: schema.Int64},
			{Name: "name", Type: schema.String},
		},
	},
	schema.CreateIndex{
		Table:   "solve_post_file_event",
		Columns: []string{"id", "event_id"},
	},
	schema.CreateTable{
		Name: "solve_visit",
		Columns: []schema.Column{
			{Name: "id", Type: schema.Int64, PrimaryKey: true, AutoIncrement: true},
			{Name: "time", Type: schema.Int64},
			{Name: "account_id", Type: schema.Int64, Nullable: true},
			{Name: "session_id", Type: schema.Int64, Nullable: true},
			{Name: "host", Type: schema.String},
			{Name: "protocol", Type: schema.String},
			{Name: "method", Type: schema.String},
			{Name: "user_agent", Type: schema.String},
			{Name: "path", Type: schema.String},
			{Name: "real_ip", Type: schema.String},
			{Name: "status", Type: schema.Int64},
		},
	},
}
