name: Main
on: [push]
jobs:
  test:
    name: Test Repository
    runs-on: ubuntu-22.04
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '^1.18'
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
          curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
          dep ensure
        fi
    - name: Run tests
      run: |
        make -C safeexec
        go test -race -coverprofile=coverage.txt -covermode=atomic -coverpkg=./... ./...
      env:
        POSTGRES_HOST: localhost
        POSTGRES_PORT: 5432
        TEST_ENABLE_LOGS: 1
    - name: Upload to Codecov
      if: success() || failure()
      env:
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
      run: |
        curl -s https://codecov.io/bash | bash
  benchmark:
    name: Benchmark Repository
    runs-on: ubuntu-22.04
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '^1.18'
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
          curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
          dep ensure
        fi
    - name: Run benchmark
      run: go test -bench=. -run=- ./... | tee bench.txt
    - name: Download previous benchmark data
      uses: actions/cache@v3
      with:
        path: ./cache
        key: ${{ runner.os }}-benchmark
    - name: Store benchmark result
      uses: benchmark-action/github-action-benchmark@v1
      with:
        tool: 'go'
        output-file-path: bench.txt
        external-data-json-path: ./cache/benchmark-data.json
        fail-on-alert: true
  docker:
    name: Build Docker image
    runs-on: ubuntu-22.04
    steps:
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Setup metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: udovin/solve
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            VERSION=${{ steps.meta.outputs.version }}
